### ISSUE TITLE
Example 5 failing

### ISSUE THREAD

**Issue by ctroupin** [fair-ease/py-udal-fe-impl#8]
I've tested the code with the proposed code: `python -m fairease.udal.example` within a virtual environment in Python 3.13, Ubuntu. This generated the following error:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ctroupin/2delete/py-udal-fe-impl/fairease/udal/example.py", line 61, in <module>
    example5()
    ~~~~~~~~^^
  File "/home/ctroupin/2delete/py-udal-fe-impl/fairease/udal/example.py", line 37, in example5
    print(fe.UDAL(endpoint).execute(queryname, queryparams).data())
          ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ctroupin/2delete/py-udal-fe-impl/fairease/udal/udal.py", line 30, in execute
    return self._broker.execute(name, params)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ctroupin/2delete/py-udal-fe-impl/fairease/udal/brokers/wikidata.py", line 147, in execute
    return Result(query, self._execute_weekdays(queryParams))
                         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/ctroupin/2delete/py-udal-fe-impl/fairease/udal/brokers/wikidata.py", line 81, in _execute_weekdays
    sparqlResults = typing.cast(dict, sparql.queryAndConvert())
                                      ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ctroupin/.virtualenvs/FE/lib/python3.13/site-packages/SPARQLWrapper/Wrapper.py", line 967, in queryAndConvert
    res = self.query()
  File "/home/ctroupin/.virtualenvs/FE/lib/python3.13/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
                       ~~~~~~~~~~~^^
  File "/home/ctroupin/.virtualenvs/FE/lib/python3.13/site-packages/SPARQLWrapper/Wrapper.py", line 940, in _query
    raise e
  File "/home/ctroupin/.virtualenvs/FE/lib/python3.13/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/usr/local/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
I didn't check the details but is this expected for the example?

**Comment by jorgecunhamendes** [comment]
@ctroupin, those examples use third-party services (Wikidata), which may impose limits on requests. I just tried it, it worked for example 5, but it failed for example 6 with the same error ("HTTP Error 403: Forbidden").

**Comment by ctroupin** [comment]
OK thanks for checking. I guess we can close the issue but maybe in the README, adding what you said about the request limits would be useful.
